// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.github.dawidd6.andttt.proto;

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ApiStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ApiStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ApiRooms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ApiRooms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ApiRoom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ApiRoom_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ApiClients_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ApiClients_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ApiClient_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ApiClient_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapi.proto\022\005proto\032\nroom.proto\032\014client.p" +
      "roto\"x\n\tApiStatus\022\026\n\016num_goroutines\030\001 \001(" +
      "\005\022\036\n\026num_registered_clients\030\002 \001(\005\022 \n\030num" +
      "_unregistered_clients\030\003 \001(\005\022\021\n\tnum_rooms" +
      "\030\004 \001(\005\"5\n\010ApiRooms\022\r\n\005count\030\001 \001(\005\022\032\n\005roo" +
      "ms\030\002 \003(\0132\013.proto.Room\"$\n\007ApiRoom\022\031\n\004room" +
      "\030\001 \001(\0132\013.proto.Room\";\n\nApiClients\022\r\n\005cou" +
      "nt\030\001 \001(\005\022\036\n\007clients\030\002 \003(\0132\r.proto.Client" +
      "\"*\n\tApiClient\022\035\n\006client\030\001 \001(\0132\r.proto.Cl" +
      "ientB#\n\037com.github.dawidd6.andttt.protoP",
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.dawidd6.andttt.proto.RoomOuterClass.getDescriptor(),
          com.github.dawidd6.andttt.proto.ClientOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_ApiStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ApiStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ApiStatus_descriptor,
        new java.lang.String[] { "NumGoroutines", "NumRegisteredClients", "NumUnregisteredClients", "NumRooms", });
    internal_static_proto_ApiRooms_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ApiRooms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ApiRooms_descriptor,
        new java.lang.String[] { "Count", "Rooms", });
    internal_static_proto_ApiRoom_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_ApiRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ApiRoom_descriptor,
        new java.lang.String[] { "Room", });
    internal_static_proto_ApiClients_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_ApiClients_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ApiClients_descriptor,
        new java.lang.String[] { "Count", "Clients", });
    internal_static_proto_ApiClient_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_ApiClient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ApiClient_descriptor,
        new java.lang.String[] { "Client", });
    com.github.dawidd6.andttt.proto.RoomOuterClass.getDescriptor();
    com.github.dawidd6.andttt.proto.ClientOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
