// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.github.dawidd6.andttt.proto;

public interface ApiClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ApiClient)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Client client = 1;</code>
   */
  boolean hasClient();
  /**
   * <code>.proto.Client client = 1;</code>
   */
  com.github.dawidd6.andttt.proto.Client getClient();
  /**
   * <code>.proto.Client client = 1;</code>
   */
  com.github.dawidd6.andttt.proto.ClientOrBuilder getClientOrBuilder();
}
