// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.github.dawidd6.andttt.proto;

public interface ApiClientsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ApiClients)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   */
  int getCount();

  /**
   * <code>repeated .proto.Client clients = 2;</code>
   */
  java.util.List<com.github.dawidd6.andttt.proto.Client> 
      getClientsList();
  /**
   * <code>repeated .proto.Client clients = 2;</code>
   */
  com.github.dawidd6.andttt.proto.Client getClients(int index);
  /**
   * <code>repeated .proto.Client clients = 2;</code>
   */
  int getClientsCount();
  /**
   * <code>repeated .proto.Client clients = 2;</code>
   */
  java.util.List<? extends com.github.dawidd6.andttt.proto.ClientOrBuilder> 
      getClientsOrBuilderList();
  /**
   * <code>repeated .proto.Client clients = 2;</code>
   */
  com.github.dawidd6.andttt.proto.ClientOrBuilder getClientsOrBuilder(
      int index);
}
