// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package com.github.dawidd6.andttt.proto;

public interface ApiRoomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ApiRoom)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Room room = 1;</code>
   */
  boolean hasRoom();
  /**
   * <code>.proto.Room room = 1;</code>
   */
  com.github.dawidd6.andttt.proto.Room getRoom();
  /**
   * <code>.proto.Room room = 1;</code>
   */
  com.github.dawidd6.andttt.proto.RoomOrBuilder getRoomOrBuilder();
}
