// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.github.dawidd6.andttt.proto;

public interface EnemyDisconnectedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.EnemyDisconnectedResponse)
    com.google.protobuf.MessageOrBuilder {
}
