// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package com.github.dawidd6.andttt.proto;

public final class Enums {
  private Enums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013enums.proto\022\005proto*\324\004\n\005Error\022\010\n\004NONE\020\000" +
      "\022\r\n\tUNDEFINED\020\001\022\030\n\024CLIENT_NAME_TOO_LONG\020" +
      "\025\022\025\n\021CLIENT_NAME_EMPTY\020\002\022\025\n\021CLIENT_NAME_" +
      "TAKEN\020\003\022\025\n\021CLIENT_HAS_A_ROOM\020\004\022\026\n\022CLIENT" +
      "_HAS_NO_ROOM\020\005\022\034\n\030CLIENT_NOT_FOUND_IN_RO" +
      "OM\020\006\022\024\n\020CLIENT_NOT_FOUND\020\007\022\026\n\022CLIENT_HAS" +
      "_NO_TURN\020\010\022\030\n\024CLIENT_HAS_NO_SYMBOL\020\t\022\026\n\022" +
      "ROOM_NAME_TOO_LONG\020\024\022\023\n\017ROOM_NAME_EMPTY\020" +
      "\n\022\023\n\017ROOM_NAME_TAKEN\020\013\022\r\n\tROOM_FULL\020\014\022\022\n" +
      "\016ROOM_NOT_FOUND\020\r\022\022\n\016ROOM_NOT_EMPTY\020\016\022\033\n",
      "\027ROOM_PASSWORD_NOT_FOUND\020\026\022\032\n\026ROOM_PASSW" +
      "ORD_MISMATCH\020\027\022\032\n\026ROOM_PASSWORD_TOO_LONG" +
      "\020\030\022!\n\035ENEMY_NOT_FOUND_BUT_SHOULD_BE\020\017\022\023\n" +
      "\017ENEMY_NOT_FOUND\020\020\022\035\n\031POSITION_ALREADY_O" +
      "CCUPIED\020\021\022\031\n\025POSITION_OUT_OF_BOUND\020\022\022\025\n\021" +
      "THERE_IS_A_WINNER\020\023*C\n\007Restart\022\017\n\013UNSPEC" +
      "IFIED\020\000\022\r\n\tREQUESTED\020\001\022\014\n\010APPROVED\020\002\022\n\n\006" +
      "DENIED\020\003*\'\n\006Symbol\022\006\n\002NO\020\000\022\t\n\005CROSS\020\001\022\n\n" +
      "\006CIRCLE\020\002B#\n\037com.github.dawidd6.andttt.p" +
      "rotoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
