// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package com.github.dawidd6.andttt.proto;

public final class Enums {
  private Enums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013enums.proto\022\005proto*\315\003\n\005Error\022\010\n\004NONE\020\000" +
      "\022\r\n\tUNDEFINED\020\001\022\025\n\021CLIENT_NAME_EMPTY\020\002\022\025" +
      "\n\021CLIENT_NAME_TAKEN\020\003\022\025\n\021CLIENT_HAS_A_RO" +
      "OM\020\004\022\026\n\022CLIENT_HAS_NO_ROOM\020\005\022\034\n\030CLIENT_N" +
      "OT_FOUND_IN_ROOM\020\006\022\024\n\020CLIENT_NOT_FOUND\020\007" +
      "\022\026\n\022CLIENT_HAS_NO_TURN\020\010\022\030\n\024CLIENT_HAS_N" +
      "O_SYMBOL\020\t\022\023\n\017ROOM_NAME_EMPTY\020\n\022\023\n\017ROOM_" +
      "NAME_TAKEN\020\013\022\r\n\tROOM_FULL\020\014\022\022\n\016ROOM_NOT_" +
      "FOUND\020\r\022\022\n\016ROOM_NOT_EMPTY\020\016\022!\n\035ENEMY_NOT" +
      "_FOUND_BUT_SHOULD_BE\020\017\022\023\n\017ENEMY_NOT_FOUN",
      "D\020\020\022\035\n\031POSITION_ALREADY_OCCUPIED\020\021\022\031\n\025PO" +
      "SITION_OUT_OF_BOUND\020\022\022\025\n\021THERE_IS_A_WINN" +
      "ER\020\023*C\n\007Restart\022\017\n\013UNSPECIFIED\020\000\022\r\n\tREQU" +
      "ESTED\020\001\022\014\n\010APPROVED\020\002\022\n\n\006DENIED\020\003*\'\n\006Sym" +
      "bol\022\006\n\002NO\020\000\022\t\n\005CROSS\020\001\022\n\n\006CIRCLE\020\002B#\n\037co" +
      "m.github.dawidd6.andttt.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
