// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.dawidd6.andttt.proto;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto.TYPE}
   */
  public enum TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNDEFINED_TYPE = 0;</code>
     */
    UNDEFINED_TYPE(0),
    /**
     * <pre>
     * string name
     * </pre>
     *
     * <code>CREATE_ROOM = 1;</code>
     */
    CREATE_ROOM(1),
    /**
     * <pre>
     * string name
     * </pre>
     *
     * <code>JOIN_ROOM = 2;</code>
     */
    JOIN_ROOM(2),
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>LEAVE_ROOM = 3;</code>
     */
    LEAVE_ROOM(3),
    /**
     * <pre>
     * repeated Room rooms
     * </pre>
     *
     * <code>GET_ROOMS = 4;</code>
     */
    GET_ROOMS(4),
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>ENEMY_DISCONNECTED = 5;</code>
     */
    ENEMY_DISCONNECTED(5),
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>ENEMY_LEFT = 6;</code>
     */
    ENEMY_LEFT(6),
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>RESTART_REQUESTED = 8;</code>
     */
    RESTART_REQUESTED(8),
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>RESTART_APPROVED = 9;</code>
     */
    RESTART_APPROVED(9),
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>RESTART_DENIED = 10;</code>
     */
    RESTART_DENIED(10),
    /**
     * <pre>
     * string symbol, bool turn
     * </pre>
     *
     * <code>STARTER_PACK = 11;</code>
     */
    STARTER_PACK(11),
    /**
     * <pre>
     * int32 position
     * </pre>
     *
     * <code>MOVE = 12;</code>
     */
    MOVE(12),
    /**
     * <pre>
     * string name
     * </pre>
     *
     * <code>REGISTER_NAME = 14;</code>
     */
    REGISTER_NAME(14),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNDEFINED_TYPE = 0;</code>
     */
    public static final int UNDEFINED_TYPE_VALUE = 0;
    /**
     * <pre>
     * string name
     * </pre>
     *
     * <code>CREATE_ROOM = 1;</code>
     */
    public static final int CREATE_ROOM_VALUE = 1;
    /**
     * <pre>
     * string name
     * </pre>
     *
     * <code>JOIN_ROOM = 2;</code>
     */
    public static final int JOIN_ROOM_VALUE = 2;
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>LEAVE_ROOM = 3;</code>
     */
    public static final int LEAVE_ROOM_VALUE = 3;
    /**
     * <pre>
     * repeated Room rooms
     * </pre>
     *
     * <code>GET_ROOMS = 4;</code>
     */
    public static final int GET_ROOMS_VALUE = 4;
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>ENEMY_DISCONNECTED = 5;</code>
     */
    public static final int ENEMY_DISCONNECTED_VALUE = 5;
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>ENEMY_LEFT = 6;</code>
     */
    public static final int ENEMY_LEFT_VALUE = 6;
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>RESTART_REQUESTED = 8;</code>
     */
    public static final int RESTART_REQUESTED_VALUE = 8;
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>RESTART_APPROVED = 9;</code>
     */
    public static final int RESTART_APPROVED_VALUE = 9;
    /**
     * <pre>
     * nil
     * </pre>
     *
     * <code>RESTART_DENIED = 10;</code>
     */
    public static final int RESTART_DENIED_VALUE = 10;
    /**
     * <pre>
     * string symbol, bool turn
     * </pre>
     *
     * <code>STARTER_PACK = 11;</code>
     */
    public static final int STARTER_PACK_VALUE = 11;
    /**
     * <pre>
     * int32 position
     * </pre>
     *
     * <code>MOVE = 12;</code>
     */
    public static final int MOVE_VALUE = 12;
    /**
     * <pre>
     * string name
     * </pre>
     *
     * <code>REGISTER_NAME = 14;</code>
     */
    public static final int REGISTER_NAME_VALUE = 14;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TYPE valueOf(int value) {
      return forNumber(value);
    }

    public static TYPE forNumber(int value) {
      switch (value) {
        case 0: return UNDEFINED_TYPE;
        case 1: return CREATE_ROOM;
        case 2: return JOIN_ROOM;
        case 3: return LEAVE_ROOM;
        case 4: return GET_ROOMS;
        case 5: return ENEMY_DISCONNECTED;
        case 6: return ENEMY_LEFT;
        case 8: return RESTART_REQUESTED;
        case 9: return RESTART_APPROVED;
        case 10: return RESTART_DENIED;
        case 11: return STARTER_PACK;
        case 12: return MOVE;
        case 14: return REGISTER_NAME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TYPE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TYPE>() {
            public TYPE findValueByNumber(int number) {
              return TYPE.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.dawidd6.andttt.proto.MessageOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final TYPE[] VALUES = values();

    public static TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TYPE(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.TYPE)
  }

  /**
   * Protobuf enum {@code proto.ERROR}
   */
  public enum ERROR
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <code>UNDEFINED_ERROR = 1;</code>
     */
    UNDEFINED_ERROR(1),
    /**
     * <code>NAME_MUST_NOT_BE_EMPTY = 2;</code>
     */
    NAME_MUST_NOT_BE_EMPTY(2),
    /**
     * <code>NAME_ALREADY_TAKEN = 3;</code>
     */
    NAME_ALREADY_TAKEN(3),
    /**
     * <code>NAME_CONN_ALREADY_EXISTS = 4;</code>
     */
    NAME_CONN_ALREADY_EXISTS(4),
    /**
     * <code>CLIENT_NOT_FOUND = 5;</code>
     */
    CLIENT_NOT_FOUND(5),
    /**
     * <code>CLIENT_CONN_NOT_FOUND = 6;</code>
     */
    CLIENT_CONN_NOT_FOUND(6),
    /**
     * <code>CLIENT_ALREADY_HAS_A_ROOM = 7;</code>
     */
    CLIENT_ALREADY_HAS_A_ROOM(7),
    /**
     * <code>CLIENT_HAS_NO_ROOM = 8;</code>
     */
    CLIENT_HAS_NO_ROOM(8),
    /**
     * <code>ROOM_ALREADY_EXISTS = 9;</code>
     */
    ROOM_ALREADY_EXISTS(9),
    /**
     * <code>ROOM_NAME_EMPTY = 10;</code>
     */
    ROOM_NAME_EMPTY(10),
    /**
     * <code>ROOM_NOT_FOUND = 11;</code>
     */
    ROOM_NOT_FOUND(11),
    /**
     * <code>ROOM_NOT_EMPTY = 12;</code>
     */
    ROOM_NOT_EMPTY(12),
    /**
     * <code>ROOM_FULL = 13;</code>
     */
    ROOM_FULL(13),
    /**
     * <code>NO_CLIENTS_AVAILABLE = 14;</code>
     */
    NO_CLIENTS_AVAILABLE(14),
    /**
     * <code>NO_ROOMS_AVAILABLE = 15;</code>
     */
    NO_ROOMS_AVAILABLE(15),
    /**
     * <code>ENEMY_NOT_FOUND = 16;</code>
     */
    ENEMY_NOT_FOUND(16),
    /**
     * <code>POSITION_ALREADY_OCCUPIED = 17;</code>
     */
    POSITION_ALREADY_OCCUPIED(17),
    /**
     * <code>NIL_CONN = 18;</code>
     */
    NIL_CONN(18),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>UNDEFINED_ERROR = 1;</code>
     */
    public static final int UNDEFINED_ERROR_VALUE = 1;
    /**
     * <code>NAME_MUST_NOT_BE_EMPTY = 2;</code>
     */
    public static final int NAME_MUST_NOT_BE_EMPTY_VALUE = 2;
    /**
     * <code>NAME_ALREADY_TAKEN = 3;</code>
     */
    public static final int NAME_ALREADY_TAKEN_VALUE = 3;
    /**
     * <code>NAME_CONN_ALREADY_EXISTS = 4;</code>
     */
    public static final int NAME_CONN_ALREADY_EXISTS_VALUE = 4;
    /**
     * <code>CLIENT_NOT_FOUND = 5;</code>
     */
    public static final int CLIENT_NOT_FOUND_VALUE = 5;
    /**
     * <code>CLIENT_CONN_NOT_FOUND = 6;</code>
     */
    public static final int CLIENT_CONN_NOT_FOUND_VALUE = 6;
    /**
     * <code>CLIENT_ALREADY_HAS_A_ROOM = 7;</code>
     */
    public static final int CLIENT_ALREADY_HAS_A_ROOM_VALUE = 7;
    /**
     * <code>CLIENT_HAS_NO_ROOM = 8;</code>
     */
    public static final int CLIENT_HAS_NO_ROOM_VALUE = 8;
    /**
     * <code>ROOM_ALREADY_EXISTS = 9;</code>
     */
    public static final int ROOM_ALREADY_EXISTS_VALUE = 9;
    /**
     * <code>ROOM_NAME_EMPTY = 10;</code>
     */
    public static final int ROOM_NAME_EMPTY_VALUE = 10;
    /**
     * <code>ROOM_NOT_FOUND = 11;</code>
     */
    public static final int ROOM_NOT_FOUND_VALUE = 11;
    /**
     * <code>ROOM_NOT_EMPTY = 12;</code>
     */
    public static final int ROOM_NOT_EMPTY_VALUE = 12;
    /**
     * <code>ROOM_FULL = 13;</code>
     */
    public static final int ROOM_FULL_VALUE = 13;
    /**
     * <code>NO_CLIENTS_AVAILABLE = 14;</code>
     */
    public static final int NO_CLIENTS_AVAILABLE_VALUE = 14;
    /**
     * <code>NO_ROOMS_AVAILABLE = 15;</code>
     */
    public static final int NO_ROOMS_AVAILABLE_VALUE = 15;
    /**
     * <code>ENEMY_NOT_FOUND = 16;</code>
     */
    public static final int ENEMY_NOT_FOUND_VALUE = 16;
    /**
     * <code>POSITION_ALREADY_OCCUPIED = 17;</code>
     */
    public static final int POSITION_ALREADY_OCCUPIED_VALUE = 17;
    /**
     * <code>NIL_CONN = 18;</code>
     */
    public static final int NIL_CONN_VALUE = 18;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ERROR valueOf(int value) {
      return forNumber(value);
    }

    public static ERROR forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return UNDEFINED_ERROR;
        case 2: return NAME_MUST_NOT_BE_EMPTY;
        case 3: return NAME_ALREADY_TAKEN;
        case 4: return NAME_CONN_ALREADY_EXISTS;
        case 5: return CLIENT_NOT_FOUND;
        case 6: return CLIENT_CONN_NOT_FOUND;
        case 7: return CLIENT_ALREADY_HAS_A_ROOM;
        case 8: return CLIENT_HAS_NO_ROOM;
        case 9: return ROOM_ALREADY_EXISTS;
        case 10: return ROOM_NAME_EMPTY;
        case 11: return ROOM_NOT_FOUND;
        case 12: return ROOM_NOT_EMPTY;
        case 13: return ROOM_FULL;
        case 14: return NO_CLIENTS_AVAILABLE;
        case 15: return NO_ROOMS_AVAILABLE;
        case 16: return ENEMY_NOT_FOUND;
        case 17: return POSITION_ALREADY_OCCUPIED;
        case 18: return NIL_CONN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ERROR>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ERROR> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ERROR>() {
            public ERROR findValueByNumber(int number) {
              return ERROR.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.dawidd6.andttt.proto.MessageOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final ERROR[] VALUES = values();

    public static ERROR valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ERROR(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.ERROR)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.TYPE type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.proto.TYPE type = 1;</code>
     */
    com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE getType();

    /**
     * <code>.proto.ERROR err = 3;</code>
     */
    int getErrValue();
    /**
     * <code>.proto.ERROR err = 3;</code>
     */
    com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR getErr();

    /**
     * <code>string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string symbol = 5;</code>
     */
    java.lang.String getSymbol();
    /**
     * <code>string symbol = 5;</code>
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <code>bool turn = 6;</code>
     */
    boolean getTurn();

    /**
     * <code>int32 position = 7;</code>
     */
    int getPosition();

    /**
     * <code>repeated .proto.Room rooms = 8;</code>
     */
    java.util.List<com.github.dawidd6.andttt.proto.RoomOuterClass.Room> 
        getRoomsList();
    /**
     * <code>repeated .proto.Room rooms = 8;</code>
     */
    com.github.dawidd6.andttt.proto.RoomOuterClass.Room getRooms(int index);
    /**
     * <code>repeated .proto.Room rooms = 8;</code>
     */
    int getRoomsCount();
    /**
     * <code>repeated .proto.Room rooms = 8;</code>
     */
    java.util.List<? extends com.github.dawidd6.andttt.proto.RoomOuterClass.RoomOrBuilder> 
        getRoomsOrBuilderList();
    /**
     * <code>repeated .proto.Room rooms = 8;</code>
     */
    com.github.dawidd6.andttt.proto.RoomOuterClass.RoomOrBuilder getRoomsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      err_ = 0;
      name_ = "";
      symbol_ = "";
      turn_ = false;
      position_ = 0;
      rooms_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              err_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              symbol_ = s;
              break;
            }
            case 48: {

              turn_ = input.readBool();
              break;
            }
            case 56: {

              position_ = input.readInt32();
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                rooms_ = new java.util.ArrayList<com.github.dawidd6.andttt.proto.RoomOuterClass.Room>();
                mutable_bitField0_ |= 0x00000040;
              }
              rooms_.add(
                  input.readMessage(com.github.dawidd6.andttt.proto.RoomOuterClass.Room.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          rooms_ = java.util.Collections.unmodifiableList(rooms_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.dawidd6.andttt.proto.MessageOuterClass.internal_static_proto_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.dawidd6.andttt.proto.MessageOuterClass.internal_static_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.dawidd6.andttt.proto.MessageOuterClass.Message.class, com.github.dawidd6.andttt.proto.MessageOuterClass.Message.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.proto.TYPE type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.proto.TYPE type = 1;</code>
     */
    public com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE getType() {
      com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE result = com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE.valueOf(type_);
      return result == null ? com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE.UNRECOGNIZED : result;
    }

    public static final int ERR_FIELD_NUMBER = 3;
    private int err_;
    /**
     * <code>.proto.ERROR err = 3;</code>
     */
    public int getErrValue() {
      return err_;
    }
    /**
     * <code>.proto.ERROR err = 3;</code>
     */
    public com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR getErr() {
      com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR result = com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR.valueOf(err_);
      return result == null ? com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR.UNRECOGNIZED : result;
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYMBOL_FIELD_NUMBER = 5;
    private volatile java.lang.Object symbol_;
    /**
     * <code>string symbol = 5;</code>
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <code>string symbol = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TURN_FIELD_NUMBER = 6;
    private boolean turn_;
    /**
     * <code>bool turn = 6;</code>
     */
    public boolean getTurn() {
      return turn_;
    }

    public static final int POSITION_FIELD_NUMBER = 7;
    private int position_;
    /**
     * <code>int32 position = 7;</code>
     */
    public int getPosition() {
      return position_;
    }

    public static final int ROOMS_FIELD_NUMBER = 8;
    private java.util.List<com.github.dawidd6.andttt.proto.RoomOuterClass.Room> rooms_;
    /**
     * <code>repeated .proto.Room rooms = 8;</code>
     */
    public java.util.List<com.github.dawidd6.andttt.proto.RoomOuterClass.Room> getRoomsList() {
      return rooms_;
    }
    /**
     * <code>repeated .proto.Room rooms = 8;</code>
     */
    public java.util.List<? extends com.github.dawidd6.andttt.proto.RoomOuterClass.RoomOrBuilder> 
        getRoomsOrBuilderList() {
      return rooms_;
    }
    /**
     * <code>repeated .proto.Room rooms = 8;</code>
     */
    public int getRoomsCount() {
      return rooms_.size();
    }
    /**
     * <code>repeated .proto.Room rooms = 8;</code>
     */
    public com.github.dawidd6.andttt.proto.RoomOuterClass.Room getRooms(int index) {
      return rooms_.get(index);
    }
    /**
     * <code>repeated .proto.Room rooms = 8;</code>
     */
    public com.github.dawidd6.andttt.proto.RoomOuterClass.RoomOrBuilder getRoomsOrBuilder(
        int index) {
      return rooms_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE.UNDEFINED_TYPE.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (err_ != com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR.NONE.getNumber()) {
        output.writeEnum(3, err_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      if (!getSymbolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, symbol_);
      }
      if (turn_ != false) {
        output.writeBool(6, turn_);
      }
      if (position_ != 0) {
        output.writeInt32(7, position_);
      }
      for (int i = 0; i < rooms_.size(); i++) {
        output.writeMessage(8, rooms_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE.UNDEFINED_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (err_ != com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, err_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      if (!getSymbolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, symbol_);
      }
      if (turn_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, turn_);
      }
      if (position_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, position_);
      }
      for (int i = 0; i < rooms_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, rooms_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.dawidd6.andttt.proto.MessageOuterClass.Message)) {
        return super.equals(obj);
      }
      com.github.dawidd6.andttt.proto.MessageOuterClass.Message other = (com.github.dawidd6.andttt.proto.MessageOuterClass.Message) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && err_ == other.err_;
      result = result && getName()
          .equals(other.getName());
      result = result && getSymbol()
          .equals(other.getSymbol());
      result = result && (getTurn()
          == other.getTurn());
      result = result && (getPosition()
          == other.getPosition());
      result = result && getRoomsList()
          .equals(other.getRoomsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + err_;
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
      hash = (37 * hash) + TURN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTurn());
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition();
      if (getRoomsCount() > 0) {
        hash = (37 * hash) + ROOMS_FIELD_NUMBER;
        hash = (53 * hash) + getRoomsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.dawidd6.andttt.proto.MessageOuterClass.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Message)
        com.github.dawidd6.andttt.proto.MessageOuterClass.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.dawidd6.andttt.proto.MessageOuterClass.internal_static_proto_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.dawidd6.andttt.proto.MessageOuterClass.internal_static_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.dawidd6.andttt.proto.MessageOuterClass.Message.class, com.github.dawidd6.andttt.proto.MessageOuterClass.Message.Builder.class);
      }

      // Construct using com.github.dawidd6.andttt.proto.MessageOuterClass.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRoomsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        err_ = 0;

        name_ = "";

        symbol_ = "";

        turn_ = false;

        position_ = 0;

        if (roomsBuilder_ == null) {
          rooms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          roomsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.dawidd6.andttt.proto.MessageOuterClass.internal_static_proto_Message_descriptor;
      }

      public com.github.dawidd6.andttt.proto.MessageOuterClass.Message getDefaultInstanceForType() {
        return com.github.dawidd6.andttt.proto.MessageOuterClass.Message.getDefaultInstance();
      }

      public com.github.dawidd6.andttt.proto.MessageOuterClass.Message build() {
        com.github.dawidd6.andttt.proto.MessageOuterClass.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.dawidd6.andttt.proto.MessageOuterClass.Message buildPartial() {
        com.github.dawidd6.andttt.proto.MessageOuterClass.Message result = new com.github.dawidd6.andttt.proto.MessageOuterClass.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.err_ = err_;
        result.name_ = name_;
        result.symbol_ = symbol_;
        result.turn_ = turn_;
        result.position_ = position_;
        if (roomsBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            rooms_ = java.util.Collections.unmodifiableList(rooms_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.rooms_ = rooms_;
        } else {
          result.rooms_ = roomsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.dawidd6.andttt.proto.MessageOuterClass.Message) {
          return mergeFrom((com.github.dawidd6.andttt.proto.MessageOuterClass.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.dawidd6.andttt.proto.MessageOuterClass.Message other) {
        if (other == com.github.dawidd6.andttt.proto.MessageOuterClass.Message.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.err_ != 0) {
          setErrValue(other.getErrValue());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
          onChanged();
        }
        if (other.getTurn() != false) {
          setTurn(other.getTurn());
        }
        if (other.getPosition() != 0) {
          setPosition(other.getPosition());
        }
        if (roomsBuilder_ == null) {
          if (!other.rooms_.isEmpty()) {
            if (rooms_.isEmpty()) {
              rooms_ = other.rooms_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureRoomsIsMutable();
              rooms_.addAll(other.rooms_);
            }
            onChanged();
          }
        } else {
          if (!other.rooms_.isEmpty()) {
            if (roomsBuilder_.isEmpty()) {
              roomsBuilder_.dispose();
              roomsBuilder_ = null;
              rooms_ = other.rooms_;
              bitField0_ = (bitField0_ & ~0x00000040);
              roomsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRoomsFieldBuilder() : null;
            } else {
              roomsBuilder_.addAllMessages(other.rooms_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.dawidd6.andttt.proto.MessageOuterClass.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.dawidd6.andttt.proto.MessageOuterClass.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.proto.TYPE type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.proto.TYPE type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.TYPE type = 1;</code>
       */
      public com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE getType() {
        com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE result = com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE.valueOf(type_);
        return result == null ? com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.TYPE type = 1;</code>
       */
      public Builder setType(com.github.dawidd6.andttt.proto.MessageOuterClass.TYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.TYPE type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int err_ = 0;
      /**
       * <code>.proto.ERROR err = 3;</code>
       */
      public int getErrValue() {
        return err_;
      }
      /**
       * <code>.proto.ERROR err = 3;</code>
       */
      public Builder setErrValue(int value) {
        err_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.ERROR err = 3;</code>
       */
      public com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR getErr() {
        com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR result = com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR.valueOf(err_);
        return result == null ? com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.ERROR err = 3;</code>
       */
      public Builder setErr(com.github.dawidd6.andttt.proto.MessageOuterClass.ERROR value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        err_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.ERROR err = 3;</code>
       */
      public Builder clearErr() {
        
        err_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object symbol_ = "";
      /**
       * <code>string symbol = 5;</code>
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string symbol = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string symbol = 5;</code>
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 5;</code>
       */
      public Builder clearSymbol() {
        
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 5;</code>
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        symbol_ = value;
        onChanged();
        return this;
      }

      private boolean turn_ ;
      /**
       * <code>bool turn = 6;</code>
       */
      public boolean getTurn() {
        return turn_;
      }
      /**
       * <code>bool turn = 6;</code>
       */
      public Builder setTurn(boolean value) {
        
        turn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool turn = 6;</code>
       */
      public Builder clearTurn() {
        
        turn_ = false;
        onChanged();
        return this;
      }

      private int position_ ;
      /**
       * <code>int32 position = 7;</code>
       */
      public int getPosition() {
        return position_;
      }
      /**
       * <code>int32 position = 7;</code>
       */
      public Builder setPosition(int value) {
        
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 position = 7;</code>
       */
      public Builder clearPosition() {
        
        position_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.github.dawidd6.andttt.proto.RoomOuterClass.Room> rooms_ =
        java.util.Collections.emptyList();
      private void ensureRoomsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          rooms_ = new java.util.ArrayList<com.github.dawidd6.andttt.proto.RoomOuterClass.Room>(rooms_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.dawidd6.andttt.proto.RoomOuterClass.Room, com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder, com.github.dawidd6.andttt.proto.RoomOuterClass.RoomOrBuilder> roomsBuilder_;

      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public java.util.List<com.github.dawidd6.andttt.proto.RoomOuterClass.Room> getRoomsList() {
        if (roomsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rooms_);
        } else {
          return roomsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public int getRoomsCount() {
        if (roomsBuilder_ == null) {
          return rooms_.size();
        } else {
          return roomsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public com.github.dawidd6.andttt.proto.RoomOuterClass.Room getRooms(int index) {
        if (roomsBuilder_ == null) {
          return rooms_.get(index);
        } else {
          return roomsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public Builder setRooms(
          int index, com.github.dawidd6.andttt.proto.RoomOuterClass.Room value) {
        if (roomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomsIsMutable();
          rooms_.set(index, value);
          onChanged();
        } else {
          roomsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public Builder setRooms(
          int index, com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder builderForValue) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.set(index, builderForValue.build());
          onChanged();
        } else {
          roomsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public Builder addRooms(com.github.dawidd6.andttt.proto.RoomOuterClass.Room value) {
        if (roomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomsIsMutable();
          rooms_.add(value);
          onChanged();
        } else {
          roomsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public Builder addRooms(
          int index, com.github.dawidd6.andttt.proto.RoomOuterClass.Room value) {
        if (roomsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoomsIsMutable();
          rooms_.add(index, value);
          onChanged();
        } else {
          roomsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public Builder addRooms(
          com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder builderForValue) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.add(builderForValue.build());
          onChanged();
        } else {
          roomsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public Builder addRooms(
          int index, com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder builderForValue) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.add(index, builderForValue.build());
          onChanged();
        } else {
          roomsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public Builder addAllRooms(
          java.lang.Iterable<? extends com.github.dawidd6.andttt.proto.RoomOuterClass.Room> values) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rooms_);
          onChanged();
        } else {
          roomsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public Builder clearRooms() {
        if (roomsBuilder_ == null) {
          rooms_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          roomsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public Builder removeRooms(int index) {
        if (roomsBuilder_ == null) {
          ensureRoomsIsMutable();
          rooms_.remove(index);
          onChanged();
        } else {
          roomsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder getRoomsBuilder(
          int index) {
        return getRoomsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public com.github.dawidd6.andttt.proto.RoomOuterClass.RoomOrBuilder getRoomsOrBuilder(
          int index) {
        if (roomsBuilder_ == null) {
          return rooms_.get(index);  } else {
          return roomsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public java.util.List<? extends com.github.dawidd6.andttt.proto.RoomOuterClass.RoomOrBuilder> 
           getRoomsOrBuilderList() {
        if (roomsBuilder_ != null) {
          return roomsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rooms_);
        }
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder addRoomsBuilder() {
        return getRoomsFieldBuilder().addBuilder(
            com.github.dawidd6.andttt.proto.RoomOuterClass.Room.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder addRoomsBuilder(
          int index) {
        return getRoomsFieldBuilder().addBuilder(
            index, com.github.dawidd6.andttt.proto.RoomOuterClass.Room.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Room rooms = 8;</code>
       */
      public java.util.List<com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder> 
           getRoomsBuilderList() {
        return getRoomsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.dawidd6.andttt.proto.RoomOuterClass.Room, com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder, com.github.dawidd6.andttt.proto.RoomOuterClass.RoomOrBuilder> 
          getRoomsFieldBuilder() {
        if (roomsBuilder_ == null) {
          roomsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.dawidd6.andttt.proto.RoomOuterClass.Room, com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder, com.github.dawidd6.andttt.proto.RoomOuterClass.RoomOrBuilder>(
                  rooms_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          rooms_ = null;
        }
        return roomsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.Message)
    }

    // @@protoc_insertion_point(class_scope:proto.Message)
    private static final com.github.dawidd6.andttt.proto.MessageOuterClass.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.dawidd6.andttt.proto.MessageOuterClass.Message();
    }

    public static com.github.dawidd6.andttt.proto.MessageOuterClass.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public com.github.dawidd6.andttt.proto.MessageOuterClass.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\005proto\032\nroom.proto\"\231\001\n\007M" +
      "essage\022\031\n\004type\030\001 \001(\0162\013.proto.TYPE\022\031\n\003err" +
      "\030\003 \001(\0162\014.proto.ERROR\022\014\n\004name\030\004 \001(\t\022\016\n\006sy" +
      "mbol\030\005 \001(\t\022\014\n\004turn\030\006 \001(\010\022\020\n\010position\030\007 \001" +
      "(\005\022\032\n\005rooms\030\010 \003(\0132\013.proto.Room*\361\001\n\004TYPE\022" +
      "\022\n\016UNDEFINED_TYPE\020\000\022\017\n\013CREATE_ROOM\020\001\022\r\n\t" +
      "JOIN_ROOM\020\002\022\016\n\nLEAVE_ROOM\020\003\022\r\n\tGET_ROOMS" +
      "\020\004\022\026\n\022ENEMY_DISCONNECTED\020\005\022\016\n\nENEMY_LEFT" +
      "\020\006\022\025\n\021RESTART_REQUESTED\020\010\022\024\n\020RESTART_APP" +
      "ROVED\020\t\022\022\n\016RESTART_DENIED\020\n\022\020\n\014STARTER_P",
      "ACK\020\013\022\010\n\004MOVE\020\014\022\021\n\rREGISTER_NAME\020\016*\271\003\n\005E" +
      "RROR\022\010\n\004NONE\020\000\022\023\n\017UNDEFINED_ERROR\020\001\022\032\n\026N" +
      "AME_MUST_NOT_BE_EMPTY\020\002\022\026\n\022NAME_ALREADY_" +
      "TAKEN\020\003\022\034\n\030NAME_CONN_ALREADY_EXISTS\020\004\022\024\n" +
      "\020CLIENT_NOT_FOUND\020\005\022\031\n\025CLIENT_CONN_NOT_F" +
      "OUND\020\006\022\035\n\031CLIENT_ALREADY_HAS_A_ROOM\020\007\022\026\n" +
      "\022CLIENT_HAS_NO_ROOM\020\010\022\027\n\023ROOM_ALREADY_EX" +
      "ISTS\020\t\022\023\n\017ROOM_NAME_EMPTY\020\n\022\022\n\016ROOM_NOT_" +
      "FOUND\020\013\022\022\n\016ROOM_NOT_EMPTY\020\014\022\r\n\tROOM_FULL" +
      "\020\r\022\030\n\024NO_CLIENTS_AVAILABLE\020\016\022\026\n\022NO_ROOMS",
      "_AVAILABLE\020\017\022\023\n\017ENEMY_NOT_FOUND\020\020\022\035\n\031POS" +
      "ITION_ALREADY_OCCUPIED\020\021\022\014\n\010NIL_CONN\020\022B!" +
      "\n\037com.github.dawidd6.andttt.protob\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.dawidd6.andttt.proto.RoomOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Message_descriptor,
        new java.lang.String[] { "Type", "Err", "Name", "Symbol", "Turn", "Position", "Rooms", });
    com.github.dawidd6.andttt.proto.RoomOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
