// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.dawidd6.andttt.proto;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\005proto\032\nroom.proto\"\231\001\n\007M" +
      "essage\022\031\n\004type\030\001 \001(\0162\013.proto.TYPE\022\031\n\003err" +
      "\030\003 \001(\0162\014.proto.ERROR\022\014\n\004name\030\004 \001(\t\022\016\n\006sy" +
      "mbol\030\005 \001(\t\022\014\n\004turn\030\006 \001(\010\022\020\n\010position\030\007 \001" +
      "(\005\022\032\n\005rooms\030\010 \003(\0132\013.proto.Room*\361\001\n\004TYPE\022" +
      "\022\n\016UNDEFINED_TYPE\020\000\022\017\n\013CREATE_ROOM\020\001\022\r\n\t" +
      "JOIN_ROOM\020\002\022\016\n\nLEAVE_ROOM\020\003\022\r\n\tGET_ROOMS" +
      "\020\004\022\026\n\022ENEMY_DISCONNECTED\020\005\022\016\n\nENEMY_LEFT" +
      "\020\006\022\025\n\021RESTART_REQUESTED\020\010\022\024\n\020RESTART_APP" +
      "ROVED\020\t\022\022\n\016RESTART_DENIED\020\n\022\020\n\014STARTER_P",
      "ACK\020\013\022\010\n\004MOVE\020\014\022\021\n\rREGISTER_NAME\020\016*\271\003\n\005E" +
      "RROR\022\010\n\004NONE\020\000\022\023\n\017UNDEFINED_ERROR\020\001\022\032\n\026N" +
      "AME_MUST_NOT_BE_EMPTY\020\002\022\026\n\022NAME_ALREADY_" +
      "TAKEN\020\003\022\034\n\030NAME_CONN_ALREADY_EXISTS\020\004\022\024\n" +
      "\020CLIENT_NOT_FOUND\020\005\022\031\n\025CLIENT_CONN_NOT_F" +
      "OUND\020\006\022\035\n\031CLIENT_ALREADY_HAS_A_ROOM\020\007\022\026\n" +
      "\022CLIENT_HAS_NO_ROOM\020\010\022\027\n\023ROOM_ALREADY_EX" +
      "ISTS\020\t\022\023\n\017ROOM_NAME_EMPTY\020\n\022\022\n\016ROOM_NOT_" +
      "FOUND\020\013\022\022\n\016ROOM_NOT_EMPTY\020\014\022\r\n\tROOM_FULL" +
      "\020\r\022\030\n\024NO_CLIENTS_AVAILABLE\020\016\022\026\n\022NO_ROOMS",
      "_AVAILABLE\020\017\022\023\n\017ENEMY_NOT_FOUND\020\020\022\035\n\031POS" +
      "ITION_ALREADY_OCCUPIED\020\021\022\014\n\010NIL_CONN\020\022B#" +
      "\n\037com.github.dawidd6.andttt.protoP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.dawidd6.andttt.proto.RoomOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Message_descriptor,
        new java.lang.String[] { "Type", "Err", "Name", "Symbol", "Turn", "Position", "Rooms", });
    com.github.dawidd6.andttt.proto.RoomOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
