// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.github.dawidd6.andttt.proto;

public interface RestartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.RestartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Restart restart = 1;</code>
   */
  int getRestartValue();
  /**
   * <code>.proto.Restart restart = 1;</code>
   */
  com.github.dawidd6.andttt.proto.Restart getRestart();
}
