// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package com.github.dawidd6.andttt.proto;

/**
 * Protobuf type {@code proto.Room}
 */
public  final class Room extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Room)
    RoomOrBuilder {
  // Use Room.newBuilder() to construct.
  private Room(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Room() {
    name_ = "";
    state_ = java.util.Collections.emptyList();
    isProtected_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Room(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            com.github.dawidd6.andttt.proto.Client.Builder subBuilder = null;
            if (firstClient_ != null) {
              subBuilder = firstClient_.toBuilder();
            }
            firstClient_ = input.readMessage(com.github.dawidd6.andttt.proto.Client.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(firstClient_);
              firstClient_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.github.dawidd6.andttt.proto.Client.Builder subBuilder = null;
            if (secondClient_ != null) {
              subBuilder = secondClient_.toBuilder();
            }
            secondClient_ = input.readMessage(com.github.dawidd6.andttt.proto.Client.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(secondClient_);
              secondClient_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              state_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000008;
            }
            state_.add(rawValue);
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                state_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              state_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (since_ != null) {
              subBuilder = since_.toBuilder();
            }
            since_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(since_);
              since_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            isProtected_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        state_ = java.util.Collections.unmodifiableList(state_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.dawidd6.andttt.proto.RoomOuterClass.internal_static_proto_Room_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.dawidd6.andttt.proto.RoomOuterClass.internal_static_proto_Room_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.dawidd6.andttt.proto.Room.class, com.github.dawidd6.andttt.proto.Room.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIRST_CLIENT_FIELD_NUMBER = 2;
  private com.github.dawidd6.andttt.proto.Client firstClient_;
  /**
   * <code>.proto.Client first_client = 2;</code>
   */
  public boolean hasFirstClient() {
    return firstClient_ != null;
  }
  /**
   * <code>.proto.Client first_client = 2;</code>
   */
  public com.github.dawidd6.andttt.proto.Client getFirstClient() {
    return firstClient_ == null ? com.github.dawidd6.andttt.proto.Client.getDefaultInstance() : firstClient_;
  }
  /**
   * <code>.proto.Client first_client = 2;</code>
   */
  public com.github.dawidd6.andttt.proto.ClientOrBuilder getFirstClientOrBuilder() {
    return getFirstClient();
  }

  public static final int SECOND_CLIENT_FIELD_NUMBER = 3;
  private com.github.dawidd6.andttt.proto.Client secondClient_;
  /**
   * <code>.proto.Client second_client = 3;</code>
   */
  public boolean hasSecondClient() {
    return secondClient_ != null;
  }
  /**
   * <code>.proto.Client second_client = 3;</code>
   */
  public com.github.dawidd6.andttt.proto.Client getSecondClient() {
    return secondClient_ == null ? com.github.dawidd6.andttt.proto.Client.getDefaultInstance() : secondClient_;
  }
  /**
   * <code>.proto.Client second_client = 3;</code>
   */
  public com.github.dawidd6.andttt.proto.ClientOrBuilder getSecondClientOrBuilder() {
    return getSecondClient();
  }

  public static final int STATE_FIELD_NUMBER = 4;
  private java.util.List<java.lang.Integer> state_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, com.github.dawidd6.andttt.proto.Symbol> state_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, com.github.dawidd6.andttt.proto.Symbol>() {
            public com.github.dawidd6.andttt.proto.Symbol convert(java.lang.Integer from) {
              com.github.dawidd6.andttt.proto.Symbol result = com.github.dawidd6.andttt.proto.Symbol.valueOf(from);
              return result == null ? com.github.dawidd6.andttt.proto.Symbol.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .proto.Symbol state = 4;</code>
   */
  public java.util.List<com.github.dawidd6.andttt.proto.Symbol> getStateList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, com.github.dawidd6.andttt.proto.Symbol>(state_, state_converter_);
  }
  /**
   * <code>repeated .proto.Symbol state = 4;</code>
   */
  public int getStateCount() {
    return state_.size();
  }
  /**
   * <code>repeated .proto.Symbol state = 4;</code>
   */
  public com.github.dawidd6.andttt.proto.Symbol getState(int index) {
    return state_converter_.convert(state_.get(index));
  }
  /**
   * <code>repeated .proto.Symbol state = 4;</code>
   */
  public java.util.List<java.lang.Integer>
  getStateValueList() {
    return state_;
  }
  /**
   * <code>repeated .proto.Symbol state = 4;</code>
   */
  public int getStateValue(int index) {
    return state_.get(index);
  }
  private int stateMemoizedSerializedSize;

  public static final int SINCE_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp since_;
  /**
   * <code>.google.protobuf.Timestamp since = 5;</code>
   */
  public boolean hasSince() {
    return since_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp since = 5;</code>
   */
  public com.google.protobuf.Timestamp getSince() {
    return since_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : since_;
  }
  /**
   * <code>.google.protobuf.Timestamp since = 5;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getSinceOrBuilder() {
    return getSince();
  }

  public static final int IS_PROTECTED_FIELD_NUMBER = 6;
  private boolean isProtected_;
  /**
   * <code>bool is_protected = 6;</code>
   */
  public boolean getIsProtected() {
    return isProtected_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (firstClient_ != null) {
      output.writeMessage(2, getFirstClient());
    }
    if (secondClient_ != null) {
      output.writeMessage(3, getSecondClient());
    }
    if (getStateList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(stateMemoizedSerializedSize);
    }
    for (int i = 0; i < state_.size(); i++) {
      output.writeEnumNoTag(state_.get(i));
    }
    if (since_ != null) {
      output.writeMessage(5, getSince());
    }
    if (isProtected_ != false) {
      output.writeBool(6, isProtected_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (firstClient_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFirstClient());
    }
    if (secondClient_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSecondClient());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < state_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(state_.get(i));
      }
      size += dataSize;
      if (!getStateList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }stateMemoizedSerializedSize = dataSize;
    }
    if (since_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSince());
    }
    if (isProtected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isProtected_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.dawidd6.andttt.proto.Room)) {
      return super.equals(obj);
    }
    com.github.dawidd6.andttt.proto.Room other = (com.github.dawidd6.andttt.proto.Room) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && (hasFirstClient() == other.hasFirstClient());
    if (hasFirstClient()) {
      result = result && getFirstClient()
          .equals(other.getFirstClient());
    }
    result = result && (hasSecondClient() == other.hasSecondClient());
    if (hasSecondClient()) {
      result = result && getSecondClient()
          .equals(other.getSecondClient());
    }
    result = result && state_.equals(other.state_);
    result = result && (hasSince() == other.hasSince());
    if (hasSince()) {
      result = result && getSince()
          .equals(other.getSince());
    }
    result = result && (getIsProtected()
        == other.getIsProtected());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasFirstClient()) {
      hash = (37 * hash) + FIRST_CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getFirstClient().hashCode();
    }
    if (hasSecondClient()) {
      hash = (37 * hash) + SECOND_CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getSecondClient().hashCode();
    }
    if (getStateCount() > 0) {
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_.hashCode();
    }
    if (hasSince()) {
      hash = (37 * hash) + SINCE_FIELD_NUMBER;
      hash = (53 * hash) + getSince().hashCode();
    }
    hash = (37 * hash) + IS_PROTECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsProtected());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.dawidd6.andttt.proto.Room parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.dawidd6.andttt.proto.Room parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.dawidd6.andttt.proto.Room parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.dawidd6.andttt.proto.Room parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.dawidd6.andttt.proto.Room parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.dawidd6.andttt.proto.Room parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.dawidd6.andttt.proto.Room parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.dawidd6.andttt.proto.Room parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.dawidd6.andttt.proto.Room parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.dawidd6.andttt.proto.Room parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.dawidd6.andttt.proto.Room parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.dawidd6.andttt.proto.Room parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.dawidd6.andttt.proto.Room prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.Room}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Room)
      com.github.dawidd6.andttt.proto.RoomOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.dawidd6.andttt.proto.RoomOuterClass.internal_static_proto_Room_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.dawidd6.andttt.proto.RoomOuterClass.internal_static_proto_Room_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.dawidd6.andttt.proto.Room.class, com.github.dawidd6.andttt.proto.Room.Builder.class);
    }

    // Construct using com.github.dawidd6.andttt.proto.Room.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      if (firstClientBuilder_ == null) {
        firstClient_ = null;
      } else {
        firstClient_ = null;
        firstClientBuilder_ = null;
      }
      if (secondClientBuilder_ == null) {
        secondClient_ = null;
      } else {
        secondClient_ = null;
        secondClientBuilder_ = null;
      }
      state_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      if (sinceBuilder_ == null) {
        since_ = null;
      } else {
        since_ = null;
        sinceBuilder_ = null;
      }
      isProtected_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.dawidd6.andttt.proto.RoomOuterClass.internal_static_proto_Room_descriptor;
    }

    public com.github.dawidd6.andttt.proto.Room getDefaultInstanceForType() {
      return com.github.dawidd6.andttt.proto.Room.getDefaultInstance();
    }

    public com.github.dawidd6.andttt.proto.Room build() {
      com.github.dawidd6.andttt.proto.Room result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.dawidd6.andttt.proto.Room buildPartial() {
      com.github.dawidd6.andttt.proto.Room result = new com.github.dawidd6.andttt.proto.Room(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      if (firstClientBuilder_ == null) {
        result.firstClient_ = firstClient_;
      } else {
        result.firstClient_ = firstClientBuilder_.build();
      }
      if (secondClientBuilder_ == null) {
        result.secondClient_ = secondClient_;
      } else {
        result.secondClient_ = secondClientBuilder_.build();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        state_ = java.util.Collections.unmodifiableList(state_);
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.state_ = state_;
      if (sinceBuilder_ == null) {
        result.since_ = since_;
      } else {
        result.since_ = sinceBuilder_.build();
      }
      result.isProtected_ = isProtected_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.dawidd6.andttt.proto.Room) {
        return mergeFrom((com.github.dawidd6.andttt.proto.Room)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.dawidd6.andttt.proto.Room other) {
      if (other == com.github.dawidd6.andttt.proto.Room.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasFirstClient()) {
        mergeFirstClient(other.getFirstClient());
      }
      if (other.hasSecondClient()) {
        mergeSecondClient(other.getSecondClient());
      }
      if (!other.state_.isEmpty()) {
        if (state_.isEmpty()) {
          state_ = other.state_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureStateIsMutable();
          state_.addAll(other.state_);
        }
        onChanged();
      }
      if (other.hasSince()) {
        mergeSince(other.getSince());
      }
      if (other.getIsProtected() != false) {
        setIsProtected(other.getIsProtected());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.dawidd6.andttt.proto.Room parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.dawidd6.andttt.proto.Room) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.github.dawidd6.andttt.proto.Client firstClient_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.dawidd6.andttt.proto.Client, com.github.dawidd6.andttt.proto.Client.Builder, com.github.dawidd6.andttt.proto.ClientOrBuilder> firstClientBuilder_;
    /**
     * <code>.proto.Client first_client = 2;</code>
     */
    public boolean hasFirstClient() {
      return firstClientBuilder_ != null || firstClient_ != null;
    }
    /**
     * <code>.proto.Client first_client = 2;</code>
     */
    public com.github.dawidd6.andttt.proto.Client getFirstClient() {
      if (firstClientBuilder_ == null) {
        return firstClient_ == null ? com.github.dawidd6.andttt.proto.Client.getDefaultInstance() : firstClient_;
      } else {
        return firstClientBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.Client first_client = 2;</code>
     */
    public Builder setFirstClient(com.github.dawidd6.andttt.proto.Client value) {
      if (firstClientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        firstClient_ = value;
        onChanged();
      } else {
        firstClientBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.Client first_client = 2;</code>
     */
    public Builder setFirstClient(
        com.github.dawidd6.andttt.proto.Client.Builder builderForValue) {
      if (firstClientBuilder_ == null) {
        firstClient_ = builderForValue.build();
        onChanged();
      } else {
        firstClientBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.Client first_client = 2;</code>
     */
    public Builder mergeFirstClient(com.github.dawidd6.andttt.proto.Client value) {
      if (firstClientBuilder_ == null) {
        if (firstClient_ != null) {
          firstClient_ =
            com.github.dawidd6.andttt.proto.Client.newBuilder(firstClient_).mergeFrom(value).buildPartial();
        } else {
          firstClient_ = value;
        }
        onChanged();
      } else {
        firstClientBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.Client first_client = 2;</code>
     */
    public Builder clearFirstClient() {
      if (firstClientBuilder_ == null) {
        firstClient_ = null;
        onChanged();
      } else {
        firstClient_ = null;
        firstClientBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.Client first_client = 2;</code>
     */
    public com.github.dawidd6.andttt.proto.Client.Builder getFirstClientBuilder() {
      
      onChanged();
      return getFirstClientFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.Client first_client = 2;</code>
     */
    public com.github.dawidd6.andttt.proto.ClientOrBuilder getFirstClientOrBuilder() {
      if (firstClientBuilder_ != null) {
        return firstClientBuilder_.getMessageOrBuilder();
      } else {
        return firstClient_ == null ?
            com.github.dawidd6.andttt.proto.Client.getDefaultInstance() : firstClient_;
      }
    }
    /**
     * <code>.proto.Client first_client = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.dawidd6.andttt.proto.Client, com.github.dawidd6.andttt.proto.Client.Builder, com.github.dawidd6.andttt.proto.ClientOrBuilder> 
        getFirstClientFieldBuilder() {
      if (firstClientBuilder_ == null) {
        firstClientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.dawidd6.andttt.proto.Client, com.github.dawidd6.andttt.proto.Client.Builder, com.github.dawidd6.andttt.proto.ClientOrBuilder>(
                getFirstClient(),
                getParentForChildren(),
                isClean());
        firstClient_ = null;
      }
      return firstClientBuilder_;
    }

    private com.github.dawidd6.andttt.proto.Client secondClient_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.dawidd6.andttt.proto.Client, com.github.dawidd6.andttt.proto.Client.Builder, com.github.dawidd6.andttt.proto.ClientOrBuilder> secondClientBuilder_;
    /**
     * <code>.proto.Client second_client = 3;</code>
     */
    public boolean hasSecondClient() {
      return secondClientBuilder_ != null || secondClient_ != null;
    }
    /**
     * <code>.proto.Client second_client = 3;</code>
     */
    public com.github.dawidd6.andttt.proto.Client getSecondClient() {
      if (secondClientBuilder_ == null) {
        return secondClient_ == null ? com.github.dawidd6.andttt.proto.Client.getDefaultInstance() : secondClient_;
      } else {
        return secondClientBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.Client second_client = 3;</code>
     */
    public Builder setSecondClient(com.github.dawidd6.andttt.proto.Client value) {
      if (secondClientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        secondClient_ = value;
        onChanged();
      } else {
        secondClientBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.Client second_client = 3;</code>
     */
    public Builder setSecondClient(
        com.github.dawidd6.andttt.proto.Client.Builder builderForValue) {
      if (secondClientBuilder_ == null) {
        secondClient_ = builderForValue.build();
        onChanged();
      } else {
        secondClientBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.Client second_client = 3;</code>
     */
    public Builder mergeSecondClient(com.github.dawidd6.andttt.proto.Client value) {
      if (secondClientBuilder_ == null) {
        if (secondClient_ != null) {
          secondClient_ =
            com.github.dawidd6.andttt.proto.Client.newBuilder(secondClient_).mergeFrom(value).buildPartial();
        } else {
          secondClient_ = value;
        }
        onChanged();
      } else {
        secondClientBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.Client second_client = 3;</code>
     */
    public Builder clearSecondClient() {
      if (secondClientBuilder_ == null) {
        secondClient_ = null;
        onChanged();
      } else {
        secondClient_ = null;
        secondClientBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.Client second_client = 3;</code>
     */
    public com.github.dawidd6.andttt.proto.Client.Builder getSecondClientBuilder() {
      
      onChanged();
      return getSecondClientFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.Client second_client = 3;</code>
     */
    public com.github.dawidd6.andttt.proto.ClientOrBuilder getSecondClientOrBuilder() {
      if (secondClientBuilder_ != null) {
        return secondClientBuilder_.getMessageOrBuilder();
      } else {
        return secondClient_ == null ?
            com.github.dawidd6.andttt.proto.Client.getDefaultInstance() : secondClient_;
      }
    }
    /**
     * <code>.proto.Client second_client = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.dawidd6.andttt.proto.Client, com.github.dawidd6.andttt.proto.Client.Builder, com.github.dawidd6.andttt.proto.ClientOrBuilder> 
        getSecondClientFieldBuilder() {
      if (secondClientBuilder_ == null) {
        secondClientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.dawidd6.andttt.proto.Client, com.github.dawidd6.andttt.proto.Client.Builder, com.github.dawidd6.andttt.proto.ClientOrBuilder>(
                getSecondClient(),
                getParentForChildren(),
                isClean());
        secondClient_ = null;
      }
      return secondClientBuilder_;
    }

    private java.util.List<java.lang.Integer> state_ =
      java.util.Collections.emptyList();
    private void ensureStateIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        state_ = new java.util.ArrayList<java.lang.Integer>(state_);
        bitField0_ |= 0x00000008;
      }
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public java.util.List<com.github.dawidd6.andttt.proto.Symbol> getStateList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.github.dawidd6.andttt.proto.Symbol>(state_, state_converter_);
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public int getStateCount() {
      return state_.size();
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public com.github.dawidd6.andttt.proto.Symbol getState(int index) {
      return state_converter_.convert(state_.get(index));
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public Builder setState(
        int index, com.github.dawidd6.andttt.proto.Symbol value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureStateIsMutable();
      state_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public Builder addState(com.github.dawidd6.andttt.proto.Symbol value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureStateIsMutable();
      state_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public Builder addAllState(
        java.lang.Iterable<? extends com.github.dawidd6.andttt.proto.Symbol> values) {
      ensureStateIsMutable();
      for (com.github.dawidd6.andttt.proto.Symbol value : values) {
        state_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public Builder clearState() {
      state_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public java.util.List<java.lang.Integer>
    getStateValueList() {
      return java.util.Collections.unmodifiableList(state_);
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public int getStateValue(int index) {
      return state_.get(index);
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public Builder setStateValue(
        int index, int value) {
      ensureStateIsMutable();
      state_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public Builder addStateValue(int value) {
      ensureStateIsMutable();
      state_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .proto.Symbol state = 4;</code>
     */
    public Builder addAllStateValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureStateIsMutable();
      for (int value : values) {
        state_.add(value);
      }
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp since_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sinceBuilder_;
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    public boolean hasSince() {
      return sinceBuilder_ != null || since_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    public com.google.protobuf.Timestamp getSince() {
      if (sinceBuilder_ == null) {
        return since_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : since_;
      } else {
        return sinceBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    public Builder setSince(com.google.protobuf.Timestamp value) {
      if (sinceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        since_ = value;
        onChanged();
      } else {
        sinceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    public Builder setSince(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (sinceBuilder_ == null) {
        since_ = builderForValue.build();
        onChanged();
      } else {
        sinceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    public Builder mergeSince(com.google.protobuf.Timestamp value) {
      if (sinceBuilder_ == null) {
        if (since_ != null) {
          since_ =
            com.google.protobuf.Timestamp.newBuilder(since_).mergeFrom(value).buildPartial();
        } else {
          since_ = value;
        }
        onChanged();
      } else {
        sinceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    public Builder clearSince() {
      if (sinceBuilder_ == null) {
        since_ = null;
        onChanged();
      } else {
        since_ = null;
        sinceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getSinceBuilder() {
      
      onChanged();
      return getSinceFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getSinceOrBuilder() {
      if (sinceBuilder_ != null) {
        return sinceBuilder_.getMessageOrBuilder();
      } else {
        return since_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : since_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getSinceFieldBuilder() {
      if (sinceBuilder_ == null) {
        sinceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getSince(),
                getParentForChildren(),
                isClean());
        since_ = null;
      }
      return sinceBuilder_;
    }

    private boolean isProtected_ ;
    /**
     * <code>bool is_protected = 6;</code>
     */
    public boolean getIsProtected() {
      return isProtected_;
    }
    /**
     * <code>bool is_protected = 6;</code>
     */
    public Builder setIsProtected(boolean value) {
      
      isProtected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_protected = 6;</code>
     */
    public Builder clearIsProtected() {
      
      isProtected_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:proto.Room)
  }

  // @@protoc_insertion_point(class_scope:proto.Room)
  private static final com.github.dawidd6.andttt.proto.Room DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.dawidd6.andttt.proto.Room();
  }

  public static com.github.dawidd6.andttt.proto.Room getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Room>
      PARSER = new com.google.protobuf.AbstractParser<Room>() {
    public Room parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Room(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Room> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Room> getParserForType() {
    return PARSER;
  }

  public com.github.dawidd6.andttt.proto.Room getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

