// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package com.github.dawidd6.andttt.proto;

public final class RoomOuterClass {
  private RoomOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto.ROOM_STATUS}
   */
  public enum ROOM_STATUS
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EMPTY = 0;</code>
     */
    EMPTY(0),
    /**
     * <code>WAITING = 1;</code>
     */
    WAITING(1),
    /**
     * <code>PLAYING = 2;</code>
     */
    PLAYING(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EMPTY = 0;</code>
     */
    public static final int EMPTY_VALUE = 0;
    /**
     * <code>WAITING = 1;</code>
     */
    public static final int WAITING_VALUE = 1;
    /**
     * <code>PLAYING = 2;</code>
     */
    public static final int PLAYING_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ROOM_STATUS valueOf(int value) {
      return forNumber(value);
    }

    public static ROOM_STATUS forNumber(int value) {
      switch (value) {
        case 0: return EMPTY;
        case 1: return WAITING;
        case 2: return PLAYING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ROOM_STATUS>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ROOM_STATUS> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ROOM_STATUS>() {
            public ROOM_STATUS findValueByNumber(int number) {
              return ROOM_STATUS.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.dawidd6.andttt.proto.RoomOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ROOM_STATUS[] VALUES = values();

    public static ROOM_STATUS valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ROOM_STATUS(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.ROOM_STATUS)
  }

  public interface RoomOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Room)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .proto.Client clients = 2;</code>
     */
    java.util.List<com.github.dawidd6.andttt.proto.ClientOuterClass.Client> 
        getClientsList();
    /**
     * <code>repeated .proto.Client clients = 2;</code>
     */
    com.github.dawidd6.andttt.proto.ClientOuterClass.Client getClients(int index);
    /**
     * <code>repeated .proto.Client clients = 2;</code>
     */
    int getClientsCount();
    /**
     * <code>repeated .proto.Client clients = 2;</code>
     */
    java.util.List<? extends com.github.dawidd6.andttt.proto.ClientOuterClass.ClientOrBuilder> 
        getClientsOrBuilderList();
    /**
     * <code>repeated .proto.Client clients = 2;</code>
     */
    com.github.dawidd6.andttt.proto.ClientOuterClass.ClientOrBuilder getClientsOrBuilder(
        int index);

    /**
     * <code>.proto.ROOM_STATUS status = 3;</code>
     */
    int getStatusValue();
    /**
     * <code>.proto.ROOM_STATUS status = 3;</code>
     */
    com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS getStatus();

    /**
     * <code>repeated string state = 4;</code>
     */
    java.util.List<java.lang.String>
        getStateList();
    /**
     * <code>repeated string state = 4;</code>
     */
    int getStateCount();
    /**
     * <code>repeated string state = 4;</code>
     */
    java.lang.String getState(int index);
    /**
     * <code>repeated string state = 4;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes(int index);

    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    boolean hasSince();
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    com.google.protobuf.Timestamp getSince();
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getSinceOrBuilder();
  }
  /**
   * Protobuf type {@code proto.Room}
   */
  public  static final class Room extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Room)
      RoomOrBuilder {
    // Use Room.newBuilder() to construct.
    private Room(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Room() {
      name_ = "";
      clients_ = java.util.Collections.emptyList();
      status_ = 0;
      state_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Room(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                clients_ = new java.util.ArrayList<com.github.dawidd6.andttt.proto.ClientOuterClass.Client>();
                mutable_bitField0_ |= 0x00000002;
              }
              clients_.add(
                  input.readMessage(com.github.dawidd6.andttt.proto.ClientOuterClass.Client.parser(), extensionRegistry));
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                state_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              state_.add(s);
              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (since_ != null) {
                subBuilder = since_.toBuilder();
              }
              since_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(since_);
                since_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          clients_ = java.util.Collections.unmodifiableList(clients_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          state_ = state_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.dawidd6.andttt.proto.RoomOuterClass.internal_static_proto_Room_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.dawidd6.andttt.proto.RoomOuterClass.internal_static_proto_Room_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.dawidd6.andttt.proto.RoomOuterClass.Room.class, com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTS_FIELD_NUMBER = 2;
    private java.util.List<com.github.dawidd6.andttt.proto.ClientOuterClass.Client> clients_;
    /**
     * <code>repeated .proto.Client clients = 2;</code>
     */
    public java.util.List<com.github.dawidd6.andttt.proto.ClientOuterClass.Client> getClientsList() {
      return clients_;
    }
    /**
     * <code>repeated .proto.Client clients = 2;</code>
     */
    public java.util.List<? extends com.github.dawidd6.andttt.proto.ClientOuterClass.ClientOrBuilder> 
        getClientsOrBuilderList() {
      return clients_;
    }
    /**
     * <code>repeated .proto.Client clients = 2;</code>
     */
    public int getClientsCount() {
      return clients_.size();
    }
    /**
     * <code>repeated .proto.Client clients = 2;</code>
     */
    public com.github.dawidd6.andttt.proto.ClientOuterClass.Client getClients(int index) {
      return clients_.get(index);
    }
    /**
     * <code>repeated .proto.Client clients = 2;</code>
     */
    public com.github.dawidd6.andttt.proto.ClientOuterClass.ClientOrBuilder getClientsOrBuilder(
        int index) {
      return clients_.get(index);
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>.proto.ROOM_STATUS status = 3;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.proto.ROOM_STATUS status = 3;</code>
     */
    public com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS getStatus() {
      com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS result = com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS.valueOf(status_);
      return result == null ? com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS.UNRECOGNIZED : result;
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList state_;
    /**
     * <code>repeated string state = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStateList() {
      return state_;
    }
    /**
     * <code>repeated string state = 4;</code>
     */
    public int getStateCount() {
      return state_.size();
    }
    /**
     * <code>repeated string state = 4;</code>
     */
    public java.lang.String getState(int index) {
      return state_.get(index);
    }
    /**
     * <code>repeated string state = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes(int index) {
      return state_.getByteString(index);
    }

    public static final int SINCE_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp since_;
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    public boolean hasSince() {
      return since_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    public com.google.protobuf.Timestamp getSince() {
      return since_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : since_;
    }
    /**
     * <code>.google.protobuf.Timestamp since = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getSinceOrBuilder() {
      return getSince();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      for (int i = 0; i < clients_.size(); i++) {
        output.writeMessage(2, clients_.get(i));
      }
      if (status_ != com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS.EMPTY.getNumber()) {
        output.writeEnum(3, status_);
      }
      for (int i = 0; i < state_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, state_.getRaw(i));
      }
      if (since_ != null) {
        output.writeMessage(5, getSince());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      for (int i = 0; i < clients_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, clients_.get(i));
      }
      if (status_ != com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS.EMPTY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, status_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < state_.size(); i++) {
          dataSize += computeStringSizeNoTag(state_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStateList().size();
      }
      if (since_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getSince());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.dawidd6.andttt.proto.RoomOuterClass.Room)) {
        return super.equals(obj);
      }
      com.github.dawidd6.andttt.proto.RoomOuterClass.Room other = (com.github.dawidd6.andttt.proto.RoomOuterClass.Room) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getClientsList()
          .equals(other.getClientsList());
      result = result && status_ == other.status_;
      result = result && getStateList()
          .equals(other.getStateList());
      result = result && (hasSince() == other.hasSince());
      if (hasSince()) {
        result = result && getSince()
            .equals(other.getSince());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getClientsCount() > 0) {
        hash = (37 * hash) + CLIENTS_FIELD_NUMBER;
        hash = (53 * hash) + getClientsList().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      if (getStateCount() > 0) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getStateList().hashCode();
      }
      if (hasSince()) {
        hash = (37 * hash) + SINCE_FIELD_NUMBER;
        hash = (53 * hash) + getSince().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.dawidd6.andttt.proto.RoomOuterClass.Room prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Room}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Room)
        com.github.dawidd6.andttt.proto.RoomOuterClass.RoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.dawidd6.andttt.proto.RoomOuterClass.internal_static_proto_Room_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.dawidd6.andttt.proto.RoomOuterClass.internal_static_proto_Room_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.dawidd6.andttt.proto.RoomOuterClass.Room.class, com.github.dawidd6.andttt.proto.RoomOuterClass.Room.Builder.class);
      }

      // Construct using com.github.dawidd6.andttt.proto.RoomOuterClass.Room.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getClientsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        if (clientsBuilder_ == null) {
          clients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          clientsBuilder_.clear();
        }
        status_ = 0;

        state_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (sinceBuilder_ == null) {
          since_ = null;
        } else {
          since_ = null;
          sinceBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.dawidd6.andttt.proto.RoomOuterClass.internal_static_proto_Room_descriptor;
      }

      public com.github.dawidd6.andttt.proto.RoomOuterClass.Room getDefaultInstanceForType() {
        return com.github.dawidd6.andttt.proto.RoomOuterClass.Room.getDefaultInstance();
      }

      public com.github.dawidd6.andttt.proto.RoomOuterClass.Room build() {
        com.github.dawidd6.andttt.proto.RoomOuterClass.Room result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.dawidd6.andttt.proto.RoomOuterClass.Room buildPartial() {
        com.github.dawidd6.andttt.proto.RoomOuterClass.Room result = new com.github.dawidd6.andttt.proto.RoomOuterClass.Room(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        if (clientsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            clients_ = java.util.Collections.unmodifiableList(clients_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.clients_ = clients_;
        } else {
          result.clients_ = clientsBuilder_.build();
        }
        result.status_ = status_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          state_ = state_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.state_ = state_;
        if (sinceBuilder_ == null) {
          result.since_ = since_;
        } else {
          result.since_ = sinceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.dawidd6.andttt.proto.RoomOuterClass.Room) {
          return mergeFrom((com.github.dawidd6.andttt.proto.RoomOuterClass.Room)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.dawidd6.andttt.proto.RoomOuterClass.Room other) {
        if (other == com.github.dawidd6.andttt.proto.RoomOuterClass.Room.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (clientsBuilder_ == null) {
          if (!other.clients_.isEmpty()) {
            if (clients_.isEmpty()) {
              clients_ = other.clients_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureClientsIsMutable();
              clients_.addAll(other.clients_);
            }
            onChanged();
          }
        } else {
          if (!other.clients_.isEmpty()) {
            if (clientsBuilder_.isEmpty()) {
              clientsBuilder_.dispose();
              clientsBuilder_ = null;
              clients_ = other.clients_;
              bitField0_ = (bitField0_ & ~0x00000002);
              clientsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getClientsFieldBuilder() : null;
            } else {
              clientsBuilder_.addAllMessages(other.clients_);
            }
          }
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.state_.isEmpty()) {
          if (state_.isEmpty()) {
            state_ = other.state_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureStateIsMutable();
            state_.addAll(other.state_);
          }
          onChanged();
        }
        if (other.hasSince()) {
          mergeSince(other.getSince());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.dawidd6.andttt.proto.RoomOuterClass.Room parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.dawidd6.andttt.proto.RoomOuterClass.Room) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.github.dawidd6.andttt.proto.ClientOuterClass.Client> clients_ =
        java.util.Collections.emptyList();
      private void ensureClientsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          clients_ = new java.util.ArrayList<com.github.dawidd6.andttt.proto.ClientOuterClass.Client>(clients_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.dawidd6.andttt.proto.ClientOuterClass.Client, com.github.dawidd6.andttt.proto.ClientOuterClass.Client.Builder, com.github.dawidd6.andttt.proto.ClientOuterClass.ClientOrBuilder> clientsBuilder_;

      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public java.util.List<com.github.dawidd6.andttt.proto.ClientOuterClass.Client> getClientsList() {
        if (clientsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(clients_);
        } else {
          return clientsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public int getClientsCount() {
        if (clientsBuilder_ == null) {
          return clients_.size();
        } else {
          return clientsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public com.github.dawidd6.andttt.proto.ClientOuterClass.Client getClients(int index) {
        if (clientsBuilder_ == null) {
          return clients_.get(index);
        } else {
          return clientsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public Builder setClients(
          int index, com.github.dawidd6.andttt.proto.ClientOuterClass.Client value) {
        if (clientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClientsIsMutable();
          clients_.set(index, value);
          onChanged();
        } else {
          clientsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public Builder setClients(
          int index, com.github.dawidd6.andttt.proto.ClientOuterClass.Client.Builder builderForValue) {
        if (clientsBuilder_ == null) {
          ensureClientsIsMutable();
          clients_.set(index, builderForValue.build());
          onChanged();
        } else {
          clientsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public Builder addClients(com.github.dawidd6.andttt.proto.ClientOuterClass.Client value) {
        if (clientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClientsIsMutable();
          clients_.add(value);
          onChanged();
        } else {
          clientsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public Builder addClients(
          int index, com.github.dawidd6.andttt.proto.ClientOuterClass.Client value) {
        if (clientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClientsIsMutable();
          clients_.add(index, value);
          onChanged();
        } else {
          clientsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public Builder addClients(
          com.github.dawidd6.andttt.proto.ClientOuterClass.Client.Builder builderForValue) {
        if (clientsBuilder_ == null) {
          ensureClientsIsMutable();
          clients_.add(builderForValue.build());
          onChanged();
        } else {
          clientsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public Builder addClients(
          int index, com.github.dawidd6.andttt.proto.ClientOuterClass.Client.Builder builderForValue) {
        if (clientsBuilder_ == null) {
          ensureClientsIsMutable();
          clients_.add(index, builderForValue.build());
          onChanged();
        } else {
          clientsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public Builder addAllClients(
          java.lang.Iterable<? extends com.github.dawidd6.andttt.proto.ClientOuterClass.Client> values) {
        if (clientsBuilder_ == null) {
          ensureClientsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, clients_);
          onChanged();
        } else {
          clientsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public Builder clearClients() {
        if (clientsBuilder_ == null) {
          clients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          clientsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public Builder removeClients(int index) {
        if (clientsBuilder_ == null) {
          ensureClientsIsMutable();
          clients_.remove(index);
          onChanged();
        } else {
          clientsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public com.github.dawidd6.andttt.proto.ClientOuterClass.Client.Builder getClientsBuilder(
          int index) {
        return getClientsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public com.github.dawidd6.andttt.proto.ClientOuterClass.ClientOrBuilder getClientsOrBuilder(
          int index) {
        if (clientsBuilder_ == null) {
          return clients_.get(index);  } else {
          return clientsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public java.util.List<? extends com.github.dawidd6.andttt.proto.ClientOuterClass.ClientOrBuilder> 
           getClientsOrBuilderList() {
        if (clientsBuilder_ != null) {
          return clientsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(clients_);
        }
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public com.github.dawidd6.andttt.proto.ClientOuterClass.Client.Builder addClientsBuilder() {
        return getClientsFieldBuilder().addBuilder(
            com.github.dawidd6.andttt.proto.ClientOuterClass.Client.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public com.github.dawidd6.andttt.proto.ClientOuterClass.Client.Builder addClientsBuilder(
          int index) {
        return getClientsFieldBuilder().addBuilder(
            index, com.github.dawidd6.andttt.proto.ClientOuterClass.Client.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Client clients = 2;</code>
       */
      public java.util.List<com.github.dawidd6.andttt.proto.ClientOuterClass.Client.Builder> 
           getClientsBuilderList() {
        return getClientsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.dawidd6.andttt.proto.ClientOuterClass.Client, com.github.dawidd6.andttt.proto.ClientOuterClass.Client.Builder, com.github.dawidd6.andttt.proto.ClientOuterClass.ClientOrBuilder> 
          getClientsFieldBuilder() {
        if (clientsBuilder_ == null) {
          clientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.dawidd6.andttt.proto.ClientOuterClass.Client, com.github.dawidd6.andttt.proto.ClientOuterClass.Client.Builder, com.github.dawidd6.andttt.proto.ClientOuterClass.ClientOrBuilder>(
                  clients_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          clients_ = null;
        }
        return clientsBuilder_;
      }

      private int status_ = 0;
      /**
       * <code>.proto.ROOM_STATUS status = 3;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.proto.ROOM_STATUS status = 3;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.ROOM_STATUS status = 3;</code>
       */
      public com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS getStatus() {
        com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS result = com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS.valueOf(status_);
        return result == null ? com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.ROOM_STATUS status = 3;</code>
       */
      public Builder setStatus(com.github.dawidd6.andttt.proto.RoomOuterClass.ROOM_STATUS value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.ROOM_STATUS status = 3;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList state_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStateIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          state_ = new com.google.protobuf.LazyStringArrayList(state_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string state = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStateList() {
        return state_.getUnmodifiableView();
      }
      /**
       * <code>repeated string state = 4;</code>
       */
      public int getStateCount() {
        return state_.size();
      }
      /**
       * <code>repeated string state = 4;</code>
       */
      public java.lang.String getState(int index) {
        return state_.get(index);
      }
      /**
       * <code>repeated string state = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes(int index) {
        return state_.getByteString(index);
      }
      /**
       * <code>repeated string state = 4;</code>
       */
      public Builder setState(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStateIsMutable();
        state_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string state = 4;</code>
       */
      public Builder addState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStateIsMutable();
        state_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string state = 4;</code>
       */
      public Builder addAllState(
          java.lang.Iterable<java.lang.String> values) {
        ensureStateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, state_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string state = 4;</code>
       */
      public Builder clearState() {
        state_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string state = 4;</code>
       */
      public Builder addStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureStateIsMutable();
        state_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp since_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sinceBuilder_;
      /**
       * <code>.google.protobuf.Timestamp since = 5;</code>
       */
      public boolean hasSince() {
        return sinceBuilder_ != null || since_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp since = 5;</code>
       */
      public com.google.protobuf.Timestamp getSince() {
        if (sinceBuilder_ == null) {
          return since_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : since_;
        } else {
          return sinceBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp since = 5;</code>
       */
      public Builder setSince(com.google.protobuf.Timestamp value) {
        if (sinceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          since_ = value;
          onChanged();
        } else {
          sinceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp since = 5;</code>
       */
      public Builder setSince(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (sinceBuilder_ == null) {
          since_ = builderForValue.build();
          onChanged();
        } else {
          sinceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp since = 5;</code>
       */
      public Builder mergeSince(com.google.protobuf.Timestamp value) {
        if (sinceBuilder_ == null) {
          if (since_ != null) {
            since_ =
              com.google.protobuf.Timestamp.newBuilder(since_).mergeFrom(value).buildPartial();
          } else {
            since_ = value;
          }
          onChanged();
        } else {
          sinceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp since = 5;</code>
       */
      public Builder clearSince() {
        if (sinceBuilder_ == null) {
          since_ = null;
          onChanged();
        } else {
          since_ = null;
          sinceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp since = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getSinceBuilder() {
        
        onChanged();
        return getSinceFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp since = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getSinceOrBuilder() {
        if (sinceBuilder_ != null) {
          return sinceBuilder_.getMessageOrBuilder();
        } else {
          return since_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : since_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp since = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getSinceFieldBuilder() {
        if (sinceBuilder_ == null) {
          sinceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getSince(),
                  getParentForChildren(),
                  isClean());
          since_ = null;
        }
        return sinceBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.Room)
    }

    // @@protoc_insertion_point(class_scope:proto.Room)
    private static final com.github.dawidd6.andttt.proto.RoomOuterClass.Room DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.dawidd6.andttt.proto.RoomOuterClass.Room();
    }

    public static com.github.dawidd6.andttt.proto.RoomOuterClass.Room getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Room>
        PARSER = new com.google.protobuf.AbstractParser<Room>() {
      public Room parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Room(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Room> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Room> getParserForType() {
      return PARSER;
    }

    public com.github.dawidd6.andttt.proto.RoomOuterClass.Room getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Room_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Room_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nroom.proto\022\005proto\032\037google/protobuf/tim" +
      "estamp.proto\032\014client.proto\"\222\001\n\004Room\022\014\n\004n" +
      "ame\030\001 \001(\t\022\036\n\007clients\030\002 \003(\0132\r.proto.Clien" +
      "t\022\"\n\006status\030\003 \001(\0162\022.proto.ROOM_STATUS\022\r\n" +
      "\005state\030\004 \003(\t\022)\n\005since\030\005 \001(\0132\032.google.pro" +
      "tobuf.Timestamp*2\n\013ROOM_STATUS\022\t\n\005EMPTY\020" +
      "\000\022\013\n\007WAITING\020\001\022\013\n\007PLAYING\020\002B!\n\037com.githu" +
      "b.dawidd6.andttt.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.github.dawidd6.andttt.proto.ClientOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_Room_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Room_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Room_descriptor,
        new java.lang.String[] { "Name", "Clients", "Status", "State", "Since", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.github.dawidd6.andttt.proto.ClientOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
