// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package com.github.dawidd6.andttt.proto;

public final class RoomOuterClass {
  private RoomOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Room_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Room_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nroom.proto\022\005proto\032\037google/protobuf/tim" +
      "estamp.proto\032\014client.proto\"\222\001\n\004Room\022\014\n\004n" +
      "ame\030\001 \001(\t\022\036\n\007clients\030\002 \003(\0132\r.proto.Clien" +
      "t\022\"\n\006status\030\003 \001(\0162\022.proto.ROOM_STATUS\022\r\n" +
      "\005state\030\004 \003(\t\022)\n\005since\030\005 \001(\0132\032.google.pro" +
      "tobuf.Timestamp*2\n\013ROOM_STATUS\022\t\n\005EMPTY\020" +
      "\000\022\013\n\007WAITING\020\001\022\013\n\007PLAYING\020\002B#\n\037com.githu" +
      "b.dawidd6.andttt.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.github.dawidd6.andttt.proto.ClientOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_Room_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Room_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Room_descriptor,
        new java.lang.String[] { "Name", "Clients", "Status", "State", "Since", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.github.dawidd6.andttt.proto.ClientOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
