// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package com.github.dawidd6.andttt.proto;

/**
 * Protobuf enum {@code proto.ROOM_STATUS}
 */
public enum ROOM_STATUS
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>EMPTY = 0;</code>
   */
  EMPTY(0),
  /**
   * <code>WAITING = 1;</code>
   */
  WAITING(1),
  /**
   * <code>PLAYING = 2;</code>
   */
  PLAYING(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>EMPTY = 0;</code>
   */
  public static final int EMPTY_VALUE = 0;
  /**
   * <code>WAITING = 1;</code>
   */
  public static final int WAITING_VALUE = 1;
  /**
   * <code>PLAYING = 2;</code>
   */
  public static final int PLAYING_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ROOM_STATUS valueOf(int value) {
    return forNumber(value);
  }

  public static ROOM_STATUS forNumber(int value) {
    switch (value) {
      case 0: return EMPTY;
      case 1: return WAITING;
      case 2: return PLAYING;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ROOM_STATUS>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ROOM_STATUS> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ROOM_STATUS>() {
          public ROOM_STATUS findValueByNumber(int number) {
            return ROOM_STATUS.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.dawidd6.andttt.proto.RoomOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ROOM_STATUS[] VALUES = values();

  public static ROOM_STATUS valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ROOM_STATUS(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:proto.ROOM_STATUS)
}

