// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

package com.github.dawidd6.andttt.proto;

public interface RoomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Room)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.proto.Client first_client = 2;</code>
   */
  boolean hasFirstClient();
  /**
   * <code>.proto.Client first_client = 2;</code>
   */
  com.github.dawidd6.andttt.proto.Client getFirstClient();
  /**
   * <code>.proto.Client first_client = 2;</code>
   */
  com.github.dawidd6.andttt.proto.ClientOrBuilder getFirstClientOrBuilder();

  /**
   * <code>.proto.Client second_client = 3;</code>
   */
  boolean hasSecondClient();
  /**
   * <code>.proto.Client second_client = 3;</code>
   */
  com.github.dawidd6.andttt.proto.Client getSecondClient();
  /**
   * <code>.proto.Client second_client = 3;</code>
   */
  com.github.dawidd6.andttt.proto.ClientOrBuilder getSecondClientOrBuilder();

  /**
   * <code>repeated .proto.Symbol state = 4;</code>
   */
  java.util.List<com.github.dawidd6.andttt.proto.Symbol> getStateList();
  /**
   * <code>repeated .proto.Symbol state = 4;</code>
   */
  int getStateCount();
  /**
   * <code>repeated .proto.Symbol state = 4;</code>
   */
  com.github.dawidd6.andttt.proto.Symbol getState(int index);
  /**
   * <code>repeated .proto.Symbol state = 4;</code>
   */
  java.util.List<java.lang.Integer>
  getStateValueList();
  /**
   * <code>repeated .proto.Symbol state = 4;</code>
   */
  int getStateValue(int index);

  /**
   * <code>.google.protobuf.Timestamp since = 5;</code>
   */
  boolean hasSince();
  /**
   * <code>.google.protobuf.Timestamp since = 5;</code>
   */
  com.google.protobuf.Timestamp getSince();
  /**
   * <code>.google.protobuf.Timestamp since = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getSinceOrBuilder();

  /**
   * <code>bool is_protected = 6;</code>
   */
  boolean getIsProtected();
}
