// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.github.dawidd6.andttt.proto;

public interface StarterPackResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StarterPackResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Symbol my_symbol = 1;</code>
   */
  int getMySymbolValue();
  /**
   * <code>.proto.Symbol my_symbol = 1;</code>
   */
  com.github.dawidd6.andttt.proto.Symbol getMySymbol();

  /**
   * <code>.proto.Symbol enemy_symbol = 2;</code>
   */
  int getEnemySymbolValue();
  /**
   * <code>.proto.Symbol enemy_symbol = 2;</code>
   */
  com.github.dawidd6.andttt.proto.Symbol getEnemySymbol();

  /**
   * <code>bool my_turn = 3;</code>
   */
  boolean getMyTurn();

  /**
   * <code>bool enemy_turn = 4;</code>
   */
  boolean getEnemyTurn();

  /**
   * <code>string enemy_name = 5;</code>
   */
  java.lang.String getEnemyName();
  /**
   * <code>string enemy_name = 5;</code>
   */
  com.google.protobuf.ByteString
      getEnemyNameBytes();
}
