// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

package com.github.dawidd6.andttt.proto;

/**
 * Protobuf enum {@code proto.Symbol}
 */
public enum Symbol
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NO = 0;</code>
   */
  NO(0),
  /**
   * <code>CROSS = 1;</code>
   */
  CROSS(1),
  /**
   * <code>CIRCLE = 2;</code>
   */
  CIRCLE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NO = 0;</code>
   */
  public static final int NO_VALUE = 0;
  /**
   * <code>CROSS = 1;</code>
   */
  public static final int CROSS_VALUE = 1;
  /**
   * <code>CIRCLE = 2;</code>
   */
  public static final int CIRCLE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Symbol valueOf(int value) {
    return forNumber(value);
  }

  public static Symbol forNumber(int value) {
    switch (value) {
      case 0: return NO;
      case 1: return CROSS;
      case 2: return CIRCLE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Symbol>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Symbol> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Symbol>() {
          public Symbol findValueByNumber(int number) {
            return Symbol.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.dawidd6.andttt.proto.Enums.getDescriptor().getEnumTypes().get(2);
  }

  private static final Symbol[] VALUES = values();

  public static Symbol valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Symbol(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:proto.Symbol)
}

