name: CD (master)

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    concurrency: deployment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{github.token}}
          context: app/src/main/go
          containerRegistry: true
      - name: Deploy Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: andttt
          heroku_email: ${{github.event.pusher.email}}
          usedocker: true
