name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 8
      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build server
        working-directory: app/src/main/go
        run: go build
      - name: Test server
        working-directory: app/src/main/go
        run: go test ./...
      - name: Upload server
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: app/src/main/go/server
